import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Container from "@mui/material/Container";
import Grid from "@mui/material/Grid";
import NavBar from "@/components/nav/NavBar";
import Box from "@mui/material/Box";
import TabPanel from "@/components/nav/TabPanel";
import Typography from "@mui/material/Typography";
import React, { useContext } from "react";
import Projects from "@/components/Projects/Projects";
import { MyGlobalContext } from "@/components/GlobalContext";
import StacksComp from "@/components/Projects/StacksComp";
import Timeline from "@/components/Projects/Timeline";
import Resume from "@/components/resume/Resume";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const value = useContext(MyGlobalContext);
  return (
    <>
      <Head>
        <title>Dev by Nate | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container component={"main"} maxWidth="lg">
        <NavBar />

        <TabPanel value={value.value} index={0}>
          <Projects />
        </TabPanel>
        <TabPanel value={value.value} index={1}>
          <StacksComp />
        </TabPanel>
        <TabPanel value={value.value} index={2}>
          <Timeline />
        </TabPanel>
        <TabPanel value={value.value} index={3}>
          <Resume />
        </TabPanel>
      </Container>
    </>
  );
}
